// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskApi.Migrations;

#nullable disable

namespace task_api.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    [Migration("20250129065153_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("TaskApi.Models.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.ToTable("Task");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            Completed = false,
                            Title = "Create Task Dialog"
                        },
                        new
                        {
                            TaskId = 2,
                            Completed = false,
                            Title = "Delete Tasks"
                        },
                        new
                        {
                            TaskId = 3,
                            Completed = false,
                            Title = "Styling & Theme"
                        },
                        new
                        {
                            TaskId = 4,
                            Completed = true,
                            Title = "Create REST API Endpoint"
                        },
                        new
                        {
                            TaskId = 5,
                            Completed = true,
                            Title = "Display Task List"
                        },
                        new
                        {
                            TaskId = 6,
                            Completed = true,
                            Title = "Toggle Tasks"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
